version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: shiftrx-admin
      POSTGRES_PASSWORD: .sh1ftrX.
      POSTGRES_DB: auction_db
    ports:
      - "5432:5432"